# Generated by Django 3.2.4 on 2021-06-10 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_user_extend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UrlHome', models.CharField(default='/', max_length=100)),
                ('Image', models.TextField(blank=True, null=True)),
                ('Position', models.CharField(blank=True, max_length=100, null=True)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Block', models.BooleanField(default=False)),
                ('AuthUserID', models.OneToOneField(blank=True, db_column='AuthUserID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_extend',
            },
        ),
    ]
