# Generated by Django 3.2.4 on 2021-06-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Telefono',
        ),
    ]
