# Generated by Django 3.2.4 on 2021-06-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Conf', '0002_auto_20210609_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Block', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Materials',
            },
        ),
    ]
