# Generated by Django 3.2.4 on 2021-06-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0005_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsAddMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('MaterialID', models.ForeignKey(blank=True, db_column='MaterialID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Conf.materials')),
            ],
            options={
                'db_table': 'ProductsAddMaterials',
            },
        ),
    ]
