# Generated by Django 3.2.4 on 2021-06-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0006_productsaddmaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsaddmaterials',
            name='ProductID',
            field=models.ForeignKey(blank=True, db_column='ProductID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Conf.products'),
        ),
    ]
