# Generated by Django 3.2.4 on 2021-06-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0007_productsaddmaterials_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='Dependent',
            field=models.BooleanField(default=False),
        ),
    ]
