# Generated by Django 3.2.4 on 2021-07-06 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0009_materials_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Width', models.IntegerField()),
                ('Length', models.IntegerField()),
                ('Heigth', models.IntegerField()),
                ('Gauge', models.IntegerField()),
                ('ProductID', models.ForeignKey(blank=True, db_column='ProductID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Conf.products')),
            ],
        ),
    ]
