# Generated by Django 3.2.4 on 2021-07-06 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0010_carports'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carports',
            table='Carports',
        ),
    ]
