# Generated by Django 3.2.4 on 2021-07-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0011_alter_carports_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='carports',
            name='Certification',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
