# Generated by Django 3.2.4 on 2021-07-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0013_alter_carports_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RunNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('CreateDateTime', models.DateTimeField()),
                ('CargoDay', models.DateTimeField(blank=True, null=True)),
                ('Installer', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('SIGN', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Runs',
            },
        ),
        migrations.CreateModel(
            name='RunsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarportID', models.ForeignKey(blank=True, db_column='CarportID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Conf.carports')),
                ('RunID', models.ForeignKey(blank=True, db_column='RunID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Conf.runs')),
            ],
            options={
                'db_table': 'RunsDetail',
            },
        ),
    ]
