# Generated by Django 3.2.4 on 2021-07-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0014_runs_runsdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runs',
            old_name='SIGN',
            new_name='Sign',
        ),
    ]
