# Generated by Django 3.2.4 on 2021-07-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0015_rename_sign_runs_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='ProcessRun',
            field=models.BooleanField(default=False),
        ),
    ]
