# Generated by Django 3.2.4 on 2021-07-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0016_runs_processrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='ReadyRun',
            field=models.BooleanField(default=False),
        ),
    ]
