# Generated by Django 3.2.4 on 2021-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0018_alter_runs_runnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runs',
            old_name='Sign',
            new_name='Status',
        ),
        migrations.AddField(
            model_name='runs',
            name='InstallationDay',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
