# Generated by Django 3.2.4 on 2021-07-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0020_auto_20210717_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='NumberofCarports',
            field=models.IntegerField(default=0),
        ),
    ]
