# Generated by Django 3.2.4 on 2021-07-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conf', '0022_runs_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='carports',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carports',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carports',
            name='Customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carports',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carports',
            name='Telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carports',
            name='ZipCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
